name: Build 3DS Homebrew

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          dkp-pacman -Syu --noconfirm 3ds-dev citro2d citro3d

      - name: Build
        run: make
